project:
  type: website
  output-dir: _site

website:
  title: "Phuong Trinh – MBA Portfolio"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "Skills & Certifications"
        file: skills.qmd
      - text: "Experience"
        file: experience.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    include-after-body:
      - scripts.html
