project:
  type: website

website:
  title: "Phuong Trinh – MBA Portfolio"
  navbar:
    left:
      - text: "Home"
        file: index.md
      - text: "Projects"
        file: projects.md
      - text: "Skills & Certifications"
        file: skills.md
      - text: "Experience"
        file: experience.md
format:
  html:
    theme: cosmo
    css: styles.css
    include-after-body:
      - scripts.html
